### ISSUE TITLE
can not find hardware/tools from Teensyduino

### ISSUE THREAD

**Issue by hllhui** [rixtox/hhkb_teensy#1]
already download ' software add-on for the Arduino, but  can not find hardware/tools from Teensyduino

**Comment by rixtox** [comment]
Teensyduino is installed on top of existing Arduino software. Suppose your Arduino is installed at `/path/arduino-1.8.7`, then your Teensyduino is installed also at `/path/arduino-1.8.7`, as a plugin to the existing system.

After that, you can find the desired folder at `/path/arduino-1.8.7/hardware/tools`.
